[package]
name = "megaclite"
version = "0.1.0"
authors = ["Megaclite <https://github.com/patractlabs/megaclite>"]
edition = "2018"

[dependencies]
bls12_381 = "0.3.1"
bn = { git = "https://github.com/paritytech/bn", default-features = false }

[dev-dependencies]
hex-literal = "0.3.1"
parity-bytes = "0.1.2"
rand = "0.7.3"
