[package]
name = "megaclite"
version = "0.1.0"
authors = ["Megaclite <https://github.com/patractlabs/megaclite>"]
edition = "2018"

[dependencies]
bls = { package = "bls12_381", version = "0.3.1" }
bn = { git = "https://github.com/paritytech/bn", default-features = false }
zkp-u256 = "0.2.0"
num-bigint = "0.3"
num-traits = "0.2"

[dev-dependencies]
hex-literal = "0.2.1"
rand = { version = "0.5", features = ["i128_support"], default-features = false }
rustc-hex = { version = "2", default-features = false }

[dev-dependencies.cargo-husky]
version = "1"
features = ["user-hooks"]
default-features = false
