[workspace]
members = [
    "crates/curve",
    "crates/merkle-tree",
    "crates/eddsa",
    "tests",
]

[profile.test]
opt-level = 3
lto = "thin"
incremental = true
debug-assertions = true
debug = true