[workspace]
members = [
    "crates/curve",
    "crates/curve/arkworks",
    "crates/curve/matter-labs",
    "crates/curve/zcash",
    "tests",
]

[profile.test]
opt-level = 3
lto = "thin"
incremental = true
debug-assertions = true
debug = true